### ISSUE TITLE
Not working using lucide-react

### ISSUE THREAD

**Issue by corentingosselin** [WarningImHack3r/vite-plugin-lucide-preprocess#12]
### What is the issue?

![image](https://github.com/user-attachments/assets/0ede7138-6385-4580-b7cf-4d836638c8be)
for lucid-react the import path is: lucide-react/dist/esm/icons/

### What are the steps to reproduce this issue?

import using lucide-react

### What were you expecting to happen?

working import

### What OS are you experiencing the problem on?

macOS

### Duplicates

- [X] I have checked that my problem has not already been mentioned recently in an existing issue

**Comment by WarningImHack3r** [comment]
Fixed, check out the 1.2.0 release or the README and tell me if it works for you!
